export const ActionTypes = {
    
    SET_LOGIN: "SET_LOGIN",

    SET_LOGOUT: "SET_LOGOUT",

    SET_RESTAURANTS: "SET_RESTAURANTS",

    GET_VENDORS: "GET_VENDORS",

    GET_RESERVATION: "GET_RESERVATION",

    GET_RESTAURANT_DETAILS: 'GET_RESTAURANT_DETAILS',

    LIST_TABLE_TYPE: 'LIST_TABLE_TYPE',

    LIST_TABLE: 'LIST_TABLE',


    // GET_FLOOR_ID: "GET_FLOOR_ID",

    // GET_TABLE_TYPE_ID: "GET_TABLE_TYPE_ID"

}